# Generated by Django 5.2.8 on 2025-11-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Is this a guest user?'),
        ),
    ]
