# Generated by Django 5.2.8 on 2025-11-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', help_text='User role: Buyer can search/view ads, Seller can post/manage ads', max_length=10),
        ),
    ]
