# Generated by Django 5.2.8 on 2025-11-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('inspector', 'Inspector')], default='buyer', help_text='User role: Buyer can search/view ads, Seller can post/manage ads, Inspector can perform vehicle inspections', max_length=10),
        ),
    ]
