# Generated by Django 5.2.8 on 2025-11-12 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField(blank=True, help_text='Mileage in kilometers', null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sold', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'cars_car',
                'ordering': ['-date_posted'],
            },
        ),
    ]
