# Generated by Django 5.2.8 on 2025-11-12 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have viewed this car', related_name='viewed_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
