# Generated by Django 5.2.8 on 2025-11-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='declined_reason',
            field=models.TextField(blank=True, help_text='Reason for declining the listing'),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('published', 'Published'), ('declined', 'Declined')], default='pending', help_text='Moderation status of the listing', max_length=20),
        ),
    ]
