# Generated by Django 5.2.8 on 2025-11-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspectionreport_inspectionphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionreport',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='rust_condition',
        ),
    ]
